const ERR_REDIS_NOT_INITIALIZED = "ERR_REDIS_NOT_INITIALIZED";

const ERR_ONGS_DUPLICATE_EMAIL = "ERR_ONGS_DUPLICATE_EMAIL";

module.exports = {
  ERR_REDIS_NOT_INITIALIZED,
  ERR_ONGS_DUPLICATE_EMAIL,
};
