exports.ERR_REDIS_NOT_INITIALIZED = "ERR_REDIS_NOT_INITIALIZED";

exports.ERR_ONGS_DUPLICATE_EMAIL = "ERR_ONGS_DUPLICATE_EMAIL";

exports.ERR_ONGS_NOT_FOUND = "ERR_ONGS_NOT_FOUND";

exports.ERR_ONGS_INVALID_PASSWORD = "ERR_ONGS_INVALID_PASSWORD";

exports.ERR_GENERATE_TOKEN = "ERR_GENERATE_TOKEN";

exports.ERR_INVALID_TOKEN = "ERR_INVALID_TOKEN";
