exports.ALGORITHM = "HS256";
exports.DEFAULT_EXPIRATION_MINUTE = 60 * 1;
exports.LOGIN_EXPIRATION_MINUTES = 60 * 9;
exports.PRE_LOGIN_EXPIRATION_MINUTES = 60 * 1;
exports.BLACKLIST_TOKEN_CACHE_PREFIX = "blacklistTokens:";
